## change netdrive to mount external hdd, otherwise should be plug and play as long as the folders exist. Finder way to automate, probably will do it themselves.
services:
  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /documents/docker/radarr/data:/config
      - /mnt/NAMEOFDRIVE/movies:/movies #optional
      - /mnt/NAMEOFDRIVE/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  # https://hub.docker.com/r/linuxserver/readarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /documents/docker/data:/config
      - /mnt/NAMEOFDRIVE/books:/books #optional
      - /mnt/NAMEOFDRIVE/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /documents/docker/sonarr/data:/config
      - /mnt/NAMEOFDRIVE/tvseries:/tv #optional
      - /mnt/NAMEOFDRIVE/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-jackett/#usage
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /documents/docker/jackett/data:/config
      - /documents/docker/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

    # no idea how to use yet https://github.com/louislam/uptime-kuma
  uptime-kuma:
        image: louislam/uptime-kuma
        container_name: uptime-kuma
        volumes:
            - ./uptime-kuma:/app/data
        ports:
            - 3001:3001    
        restart: unless-stopped

  # may not need, may set up on vps
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /documents/docker/qbittorrent/appdata:/config
      - /mnt/NAMEOFDRIVE/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  # https://docs.jellyseerr.dev/getting-started/docker?docker-methods=docker-compose
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Sydney
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /documents/docker/jellyseer/appdata/config:/app/config
    restart: unless-stopped
    
